### PR TITLE
Fix warning caused by "lvha" implementation

### PR DESCRIPTION
**Pull request by tpq**
Fixed bug in the "lvha" implementation where ALDEx2 checks whether `denom == "lvha"`.

This causes a non-critical warning when denom is a user-specified vector, e.g.:

```
library(ALDEx2)
data(selex)
group <- c(rep("A", 7), rep("B", 7))
ALDEx2::aldex(selex[1:50,], group, denom = 1:3)
```

### CODE REVIEW

**Comment by vmikk** [comment]
Dear @tpq, thank you for the commit, but I believe that the development ALDEx2 repo should be here: https://github.com/ggloor/ALDEx2_dev
I have no idea why the original repository (https://github.com/ggloor/ALDEx2) become a fork of my repo (https://github.com/vmikk/ALDEx2). It could be GitHub bug.
Maybe Greg Gloor (@ggloor) can help us to resolve this problem.

**Comment by tpq** [comment]
Ha! Yes! I had actually submitted the pull request to `ggloor/ALDEx2`, but realized too late that this automatically pushed to your branch. As far as I can tell, ALDEx2_dev is out-of-date. Interestingly, Bioconductor lists `ggloor/ALDEx2` as the official branch, which you seem to own!!

@ggloor -- it may be advisable to contact GitHub support via https://github.com/contact and request "To detach the fork and turn it into a standalone repository" (reference: https://stackoverflow.com/questions/18390249/github-make-fork-an-own-project). This will make it much easier for me (and others) to contribute code to the project.

**Comment by ggloor** [comment]
Thanks for letting me know. I'll contact them. The repository for bioconductor should be https://github.com/ggloor/ALDEx_bioc. strange

**Comment by tpq** [comment]
Thanks @ggloor, will re-submit to ALDEx_bioc!

**Pull request closed without merging**
